// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActivityModel.proto

package org.savara.sam.activity;

public final class ActivityModel {
  private ActivityModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ComponentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string location = 1;
    boolean hasLocation();
    String getLocation();
    
    // optional string locationType = 2;
    boolean hasLocationType();
    String getLocationType();
    
    // optional string containerId = 3;
    boolean hasContainerId();
    String getContainerId();
    
    // optional string application = 4;
    boolean hasApplication();
    String getApplication();
    
    // optional string component = 5;
    boolean hasComponent();
    String getComponent();
    
    // optional string componentType = 6;
    boolean hasComponentType();
    String getComponentType();
    
    // optional string instanceId = 7;
    boolean hasInstanceId();
    String getInstanceId();
    
    // optional string threadId = 8;
    boolean hasThreadId();
    String getThreadId();
  }
  public static final class Component extends
      com.google.protobuf.GeneratedMessage
      implements ComponentOrBuilder {
    // Use Component.newBuilder() to construct.
    private Component(Builder builder) {
      super(builder);
    }
    private Component(boolean noInit) {}
    
    private static final Component defaultInstance;
    public static Component getDefaultInstance() {
      return defaultInstance;
    }
    
    public Component getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Component_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Component_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string location = 1;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private java.lang.Object location_;
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          location_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string locationType = 2;
    public static final int LOCATIONTYPE_FIELD_NUMBER = 2;
    private java.lang.Object locationType_;
    public boolean hasLocationType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLocationType() {
      java.lang.Object ref = locationType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locationType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocationTypeBytes() {
      java.lang.Object ref = locationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string containerId = 3;
    public static final int CONTAINERID_FIELD_NUMBER = 3;
    private java.lang.Object containerId_;
    public boolean hasContainerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getContainerId() {
      java.lang.Object ref = containerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          containerId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContainerIdBytes() {
      java.lang.Object ref = containerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        containerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string application = 4;
    public static final int APPLICATION_FIELD_NUMBER = 4;
    private java.lang.Object application_;
    public boolean hasApplication() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getApplication() {
      java.lang.Object ref = application_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          application_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApplicationBytes() {
      java.lang.Object ref = application_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        application_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string component = 5;
    public static final int COMPONENT_FIELD_NUMBER = 5;
    private java.lang.Object component_;
    public boolean hasComponent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getComponent() {
      java.lang.Object ref = component_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          component_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getComponentBytes() {
      java.lang.Object ref = component_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        component_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string componentType = 6;
    public static final int COMPONENTTYPE_FIELD_NUMBER = 6;
    private java.lang.Object componentType_;
    public boolean hasComponentType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getComponentType() {
      java.lang.Object ref = componentType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          componentType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getComponentTypeBytes() {
      java.lang.Object ref = componentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        componentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string instanceId = 7;
    public static final int INSTANCEID_FIELD_NUMBER = 7;
    private java.lang.Object instanceId_;
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getInstanceId() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          instanceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInstanceIdBytes() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        instanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string threadId = 8;
    public static final int THREADID_FIELD_NUMBER = 8;
    private java.lang.Object threadId_;
    public boolean hasThreadId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getThreadId() {
      java.lang.Object ref = threadId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          threadId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getThreadIdBytes() {
      java.lang.Object ref = threadId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        threadId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      location_ = "";
      locationType_ = "";
      containerId_ = "";
      application_ = "";
      component_ = "";
      componentType_ = "";
      instanceId_ = "";
      threadId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLocationBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLocationTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContainerIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getApplicationBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getComponentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getComponentTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getInstanceIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getThreadIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLocationBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLocationTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContainerIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getApplicationBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getComponentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getComponentTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getInstanceIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getThreadIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ActivityModel.Component parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Component parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.savara.sam.activity.ActivityModel.Component prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.savara.sam.activity.ActivityModel.ComponentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Component_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Component_fieldAccessorTable;
      }
      
      // Construct using org.savara.sam.activity.ActivityModel.Component.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        location_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        locationType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        containerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        application_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        component_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        componentType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        instanceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        threadId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.savara.sam.activity.ActivityModel.Component.getDescriptor();
      }
      
      public org.savara.sam.activity.ActivityModel.Component getDefaultInstanceForType() {
        return org.savara.sam.activity.ActivityModel.Component.getDefaultInstance();
      }
      
      public org.savara.sam.activity.ActivityModel.Component build() {
        org.savara.sam.activity.ActivityModel.Component result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.savara.sam.activity.ActivityModel.Component buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.savara.sam.activity.ActivityModel.Component result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.savara.sam.activity.ActivityModel.Component buildPartial() {
        org.savara.sam.activity.ActivityModel.Component result = new org.savara.sam.activity.ActivityModel.Component(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.location_ = location_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.locationType_ = locationType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.containerId_ = containerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.application_ = application_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.component_ = component_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.componentType_ = componentType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.instanceId_ = instanceId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.threadId_ = threadId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.savara.sam.activity.ActivityModel.Component) {
          return mergeFrom((org.savara.sam.activity.ActivityModel.Component)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.savara.sam.activity.ActivityModel.Component other) {
        if (other == org.savara.sam.activity.ActivityModel.Component.getDefaultInstance()) return this;
        if (other.hasLocation()) {
          setLocation(other.getLocation());
        }
        if (other.hasLocationType()) {
          setLocationType(other.getLocationType());
        }
        if (other.hasContainerId()) {
          setContainerId(other.getContainerId());
        }
        if (other.hasApplication()) {
          setApplication(other.getApplication());
        }
        if (other.hasComponent()) {
          setComponent(other.getComponent());
        }
        if (other.hasComponentType()) {
          setComponentType(other.getComponentType());
        }
        if (other.hasInstanceId()) {
          setInstanceId(other.getInstanceId());
        }
        if (other.hasThreadId()) {
          setThreadId(other.getThreadId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              location_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              locationType_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              containerId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              application_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              component_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              componentType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              instanceId_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              threadId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string location = 1;
      private java.lang.Object location_ = "";
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        location_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      void setLocation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        location_ = value;
        onChanged();
      }
      
      // optional string locationType = 2;
      private java.lang.Object locationType_ = "";
      public boolean hasLocationType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLocationType() {
        java.lang.Object ref = locationType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locationType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocationType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        locationType_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocationType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        locationType_ = getDefaultInstance().getLocationType();
        onChanged();
        return this;
      }
      void setLocationType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        locationType_ = value;
        onChanged();
      }
      
      // optional string containerId = 3;
      private java.lang.Object containerId_ = "";
      public boolean hasContainerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getContainerId() {
        java.lang.Object ref = containerId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          containerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContainerId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        containerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearContainerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        containerId_ = getDefaultInstance().getContainerId();
        onChanged();
        return this;
      }
      void setContainerId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        containerId_ = value;
        onChanged();
      }
      
      // optional string application = 4;
      private java.lang.Object application_ = "";
      public boolean hasApplication() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getApplication() {
        java.lang.Object ref = application_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          application_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApplication(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        application_ = value;
        onChanged();
        return this;
      }
      public Builder clearApplication() {
        bitField0_ = (bitField0_ & ~0x00000008);
        application_ = getDefaultInstance().getApplication();
        onChanged();
        return this;
      }
      void setApplication(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        application_ = value;
        onChanged();
      }
      
      // optional string component = 5;
      private java.lang.Object component_ = "";
      public boolean hasComponent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getComponent() {
        java.lang.Object ref = component_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          component_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setComponent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        component_ = value;
        onChanged();
        return this;
      }
      public Builder clearComponent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        component_ = getDefaultInstance().getComponent();
        onChanged();
        return this;
      }
      void setComponent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        component_ = value;
        onChanged();
      }
      
      // optional string componentType = 6;
      private java.lang.Object componentType_ = "";
      public boolean hasComponentType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getComponentType() {
        java.lang.Object ref = componentType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          componentType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setComponentType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        componentType_ = value;
        onChanged();
        return this;
      }
      public Builder clearComponentType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        componentType_ = getDefaultInstance().getComponentType();
        onChanged();
        return this;
      }
      void setComponentType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        componentType_ = value;
        onChanged();
      }
      
      // optional string instanceId = 7;
      private java.lang.Object instanceId_ = "";
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getInstanceId() {
        java.lang.Object ref = instanceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          instanceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInstanceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        instanceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        instanceId_ = getDefaultInstance().getInstanceId();
        onChanged();
        return this;
      }
      void setInstanceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        instanceId_ = value;
        onChanged();
      }
      
      // optional string threadId = 8;
      private java.lang.Object threadId_ = "";
      public boolean hasThreadId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getThreadId() {
        java.lang.Object ref = threadId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          threadId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setThreadId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        threadId_ = value;
        onChanged();
        return this;
      }
      public Builder clearThreadId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        threadId_ = getDefaultInstance().getThreadId();
        onChanged();
        return this;
      }
      void setThreadId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        threadId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.savara.sam.activity.Component)
    }
    
    static {
      defaultInstance = new Component(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.savara.sam.activity.Component)
  }
  
  public interface ActivityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // required .org.savara.sam.activity.Component component = 2;
    boolean hasComponent();
    org.savara.sam.activity.ActivityModel.Component getComponent();
    org.savara.sam.activity.ActivityModel.ComponentOrBuilder getComponentOrBuilder();
    
    // required int64 timestamp = 3;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional string principal = 4;
    boolean hasPrincipal();
    String getPrincipal();
    
    // optional .org.savara.sam.activity.ServiceInvocation serviceInvocation = 5;
    boolean hasServiceInvocation();
    org.savara.sam.activity.ServiceModel.ServiceInvocation getServiceInvocation();
    org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder getServiceInvocationOrBuilder();
  }
  public static final class Activity extends
      com.google.protobuf.GeneratedMessage
      implements ActivityOrBuilder {
    // Use Activity.newBuilder() to construct.
    private Activity(Builder builder) {
      super(builder);
    }
    private Activity(boolean noInit) {}
    
    private static final Activity defaultInstance;
    public static Activity getDefaultInstance() {
      return defaultInstance;
    }
    
    public Activity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Activity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Activity_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .org.savara.sam.activity.Component component = 2;
    public static final int COMPONENT_FIELD_NUMBER = 2;
    private org.savara.sam.activity.ActivityModel.Component component_;
    public boolean hasComponent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.savara.sam.activity.ActivityModel.Component getComponent() {
      return component_;
    }
    public org.savara.sam.activity.ActivityModel.ComponentOrBuilder getComponentOrBuilder() {
      return component_;
    }
    
    // required int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional string principal = 4;
    public static final int PRINCIPAL_FIELD_NUMBER = 4;
    private java.lang.Object principal_;
    public boolean hasPrincipal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPrincipal() {
      java.lang.Object ref = principal_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          principal_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPrincipalBytes() {
      java.lang.Object ref = principal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        principal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .org.savara.sam.activity.ServiceInvocation serviceInvocation = 5;
    public static final int SERVICEINVOCATION_FIELD_NUMBER = 5;
    private org.savara.sam.activity.ServiceModel.ServiceInvocation serviceInvocation_;
    public boolean hasServiceInvocation() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public org.savara.sam.activity.ServiceModel.ServiceInvocation getServiceInvocation() {
      return serviceInvocation_;
    }
    public org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder getServiceInvocationOrBuilder() {
      return serviceInvocation_;
    }
    
    private void initFields() {
      id_ = "";
      component_ = org.savara.sam.activity.ActivityModel.Component.getDefaultInstance();
      timestamp_ = 0L;
      principal_ = "";
      serviceInvocation_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasComponent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasServiceInvocation()) {
        if (!getServiceInvocation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, component_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPrincipalBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, serviceInvocation_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, component_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPrincipalBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, serviceInvocation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ActivityModel.Activity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.savara.sam.activity.ActivityModel.Activity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.savara.sam.activity.ActivityModel.ActivityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Activity_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.savara.sam.activity.ActivityModel.internal_static_org_savara_sam_activity_Activity_fieldAccessorTable;
      }
      
      // Construct using org.savara.sam.activity.ActivityModel.Activity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getComponentFieldBuilder();
          getServiceInvocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (componentBuilder_ == null) {
          component_ = org.savara.sam.activity.ActivityModel.Component.getDefaultInstance();
        } else {
          componentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        principal_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (serviceInvocationBuilder_ == null) {
          serviceInvocation_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance();
        } else {
          serviceInvocationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.savara.sam.activity.ActivityModel.Activity.getDescriptor();
      }
      
      public org.savara.sam.activity.ActivityModel.Activity getDefaultInstanceForType() {
        return org.savara.sam.activity.ActivityModel.Activity.getDefaultInstance();
      }
      
      public org.savara.sam.activity.ActivityModel.Activity build() {
        org.savara.sam.activity.ActivityModel.Activity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.savara.sam.activity.ActivityModel.Activity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.savara.sam.activity.ActivityModel.Activity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.savara.sam.activity.ActivityModel.Activity buildPartial() {
        org.savara.sam.activity.ActivityModel.Activity result = new org.savara.sam.activity.ActivityModel.Activity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (componentBuilder_ == null) {
          result.component_ = component_;
        } else {
          result.component_ = componentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.principal_ = principal_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (serviceInvocationBuilder_ == null) {
          result.serviceInvocation_ = serviceInvocation_;
        } else {
          result.serviceInvocation_ = serviceInvocationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.savara.sam.activity.ActivityModel.Activity) {
          return mergeFrom((org.savara.sam.activity.ActivityModel.Activity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.savara.sam.activity.ActivityModel.Activity other) {
        if (other == org.savara.sam.activity.ActivityModel.Activity.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasComponent()) {
          mergeComponent(other.getComponent());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasPrincipal()) {
          setPrincipal(other.getPrincipal());
        }
        if (other.hasServiceInvocation()) {
          mergeServiceInvocation(other.getServiceInvocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasComponent()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (hasServiceInvocation()) {
          if (!getServiceInvocation().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              org.savara.sam.activity.ActivityModel.Component.Builder subBuilder = org.savara.sam.activity.ActivityModel.Component.newBuilder();
              if (hasComponent()) {
                subBuilder.mergeFrom(getComponent());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setComponent(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              principal_ = input.readBytes();
              break;
            }
            case 42: {
              org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder subBuilder = org.savara.sam.activity.ServiceModel.ServiceInvocation.newBuilder();
              if (hasServiceInvocation()) {
                subBuilder.mergeFrom(getServiceInvocation());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setServiceInvocation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required .org.savara.sam.activity.Component component = 2;
      private org.savara.sam.activity.ActivityModel.Component component_ = org.savara.sam.activity.ActivityModel.Component.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.savara.sam.activity.ActivityModel.Component, org.savara.sam.activity.ActivityModel.Component.Builder, org.savara.sam.activity.ActivityModel.ComponentOrBuilder> componentBuilder_;
      public boolean hasComponent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.savara.sam.activity.ActivityModel.Component getComponent() {
        if (componentBuilder_ == null) {
          return component_;
        } else {
          return componentBuilder_.getMessage();
        }
      }
      public Builder setComponent(org.savara.sam.activity.ActivityModel.Component value) {
        if (componentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          component_ = value;
          onChanged();
        } else {
          componentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setComponent(
          org.savara.sam.activity.ActivityModel.Component.Builder builderForValue) {
        if (componentBuilder_ == null) {
          component_ = builderForValue.build();
          onChanged();
        } else {
          componentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeComponent(org.savara.sam.activity.ActivityModel.Component value) {
        if (componentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              component_ != org.savara.sam.activity.ActivityModel.Component.getDefaultInstance()) {
            component_ =
              org.savara.sam.activity.ActivityModel.Component.newBuilder(component_).mergeFrom(value).buildPartial();
          } else {
            component_ = value;
          }
          onChanged();
        } else {
          componentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearComponent() {
        if (componentBuilder_ == null) {
          component_ = org.savara.sam.activity.ActivityModel.Component.getDefaultInstance();
          onChanged();
        } else {
          componentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.savara.sam.activity.ActivityModel.Component.Builder getComponentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getComponentFieldBuilder().getBuilder();
      }
      public org.savara.sam.activity.ActivityModel.ComponentOrBuilder getComponentOrBuilder() {
        if (componentBuilder_ != null) {
          return componentBuilder_.getMessageOrBuilder();
        } else {
          return component_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.savara.sam.activity.ActivityModel.Component, org.savara.sam.activity.ActivityModel.Component.Builder, org.savara.sam.activity.ActivityModel.ComponentOrBuilder> 
          getComponentFieldBuilder() {
        if (componentBuilder_ == null) {
          componentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.savara.sam.activity.ActivityModel.Component, org.savara.sam.activity.ActivityModel.Component.Builder, org.savara.sam.activity.ActivityModel.ComponentOrBuilder>(
                  component_,
                  getParentForChildren(),
                  isClean());
          component_ = null;
        }
        return componentBuilder_;
      }
      
      // required int64 timestamp = 3;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string principal = 4;
      private java.lang.Object principal_ = "";
      public boolean hasPrincipal() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPrincipal() {
        java.lang.Object ref = principal_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          principal_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPrincipal(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        principal_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrincipal() {
        bitField0_ = (bitField0_ & ~0x00000008);
        principal_ = getDefaultInstance().getPrincipal();
        onChanged();
        return this;
      }
      void setPrincipal(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        principal_ = value;
        onChanged();
      }
      
      // optional .org.savara.sam.activity.ServiceInvocation serviceInvocation = 5;
      private org.savara.sam.activity.ServiceModel.ServiceInvocation serviceInvocation_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.savara.sam.activity.ServiceModel.ServiceInvocation, org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder, org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder> serviceInvocationBuilder_;
      public boolean hasServiceInvocation() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public org.savara.sam.activity.ServiceModel.ServiceInvocation getServiceInvocation() {
        if (serviceInvocationBuilder_ == null) {
          return serviceInvocation_;
        } else {
          return serviceInvocationBuilder_.getMessage();
        }
      }
      public Builder setServiceInvocation(org.savara.sam.activity.ServiceModel.ServiceInvocation value) {
        if (serviceInvocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serviceInvocation_ = value;
          onChanged();
        } else {
          serviceInvocationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setServiceInvocation(
          org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder builderForValue) {
        if (serviceInvocationBuilder_ == null) {
          serviceInvocation_ = builderForValue.build();
          onChanged();
        } else {
          serviceInvocationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeServiceInvocation(org.savara.sam.activity.ServiceModel.ServiceInvocation value) {
        if (serviceInvocationBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              serviceInvocation_ != org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance()) {
            serviceInvocation_ =
              org.savara.sam.activity.ServiceModel.ServiceInvocation.newBuilder(serviceInvocation_).mergeFrom(value).buildPartial();
          } else {
            serviceInvocation_ = value;
          }
          onChanged();
        } else {
          serviceInvocationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearServiceInvocation() {
        if (serviceInvocationBuilder_ == null) {
          serviceInvocation_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance();
          onChanged();
        } else {
          serviceInvocationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder getServiceInvocationBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getServiceInvocationFieldBuilder().getBuilder();
      }
      public org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder getServiceInvocationOrBuilder() {
        if (serviceInvocationBuilder_ != null) {
          return serviceInvocationBuilder_.getMessageOrBuilder();
        } else {
          return serviceInvocation_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.savara.sam.activity.ServiceModel.ServiceInvocation, org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder, org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder> 
          getServiceInvocationFieldBuilder() {
        if (serviceInvocationBuilder_ == null) {
          serviceInvocationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.savara.sam.activity.ServiceModel.ServiceInvocation, org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder, org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder>(
                  serviceInvocation_,
                  getParentForChildren(),
                  isClean());
          serviceInvocation_ = null;
        }
        return serviceInvocationBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.savara.sam.activity.Activity)
    }
    
    static {
      defaultInstance = new Activity(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.savara.sam.activity.Activity)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_savara_sam_activity_Component_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_savara_sam_activity_Component_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_savara_sam_activity_Activity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_savara_sam_activity_Activity_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ActivityModel.proto\022\027org.savara.sam.ac" +
      "tivity\032\022ServiceModel.proto\"\255\001\n\tComponent" +
      "\022\020\n\010location\030\001 \001(\t\022\024\n\014locationType\030\002 \001(\t" +
      "\022\023\n\013containerId\030\003 \001(\t\022\023\n\013application\030\004 \001" +
      "(\t\022\021\n\tcomponent\030\005 \001(\t\022\025\n\rcomponentType\030\006" +
      " \001(\t\022\022\n\ninstanceId\030\007 \001(\t\022\020\n\010threadId\030\010 \001" +
      "(\t\"\272\001\n\010Activity\022\n\n\002id\030\001 \001(\t\0225\n\tcomponent" +
      "\030\002 \002(\0132\".org.savara.sam.activity.Compone" +
      "nt\022\021\n\ttimestamp\030\003 \002(\003\022\021\n\tprincipal\030\004 \001(\t" +
      "\022E\n\021serviceInvocation\030\005 \001(\0132*.org.savara",
      ".sam.activity.ServiceInvocationB(\n\027org.s" +
      "avara.sam.activityB\rActivityModel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_savara_sam_activity_Component_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_savara_sam_activity_Component_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_savara_sam_activity_Component_descriptor,
              new java.lang.String[] { "Location", "LocationType", "ContainerId", "Application", "Component", "ComponentType", "InstanceId", "ThreadId", },
              org.savara.sam.activity.ActivityModel.Component.class,
              org.savara.sam.activity.ActivityModel.Component.Builder.class);
          internal_static_org_savara_sam_activity_Activity_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_savara_sam_activity_Activity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_savara_sam_activity_Activity_descriptor,
              new java.lang.String[] { "Id", "Component", "Timestamp", "Principal", "ServiceInvocation", },
              org.savara.sam.activity.ActivityModel.Activity.class,
              org.savara.sam.activity.ActivityModel.Activity.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.savara.sam.activity.ServiceModel.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
