// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceModel.proto

package org.savara.sam.activity;

public final class ServiceModel {
  private ServiceModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string messageType = 1;
    boolean hasMessageType();
    String getMessageType();
    
    // optional string content = 2;
    boolean hasContent();
    String getContent();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private java.lang.Object messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          messageType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      messageType_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ServiceModel.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.savara.sam.activity.ServiceModel.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.savara.sam.activity.ServiceModel.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_Message_fieldAccessorTable;
      }
      
      // Construct using org.savara.sam.activity.ServiceModel.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        messageType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.savara.sam.activity.ServiceModel.Message.getDescriptor();
      }
      
      public org.savara.sam.activity.ServiceModel.Message getDefaultInstanceForType() {
        return org.savara.sam.activity.ServiceModel.Message.getDefaultInstance();
      }
      
      public org.savara.sam.activity.ServiceModel.Message build() {
        org.savara.sam.activity.ServiceModel.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.savara.sam.activity.ServiceModel.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.savara.sam.activity.ServiceModel.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.savara.sam.activity.ServiceModel.Message buildPartial() {
        org.savara.sam.activity.ServiceModel.Message result = new org.savara.sam.activity.ServiceModel.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.savara.sam.activity.ServiceModel.Message) {
          return mergeFrom((org.savara.sam.activity.ServiceModel.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.savara.sam.activity.ServiceModel.Message other) {
        if (other == org.savara.sam.activity.ServiceModel.Message.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              messageType_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string messageType = 1;
      private java.lang.Object messageType_ = "";
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessageType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = getDefaultInstance().getMessageType();
        onChanged();
        return this;
      }
      void setMessageType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
      }
      
      // optional string content = 2;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.savara.sam.activity.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.savara.sam.activity.Message)
  }
  
  public interface ServiceInvocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string serviceType = 1;
    boolean hasServiceType();
    String getServiceType();
    
    // optional string operation = 2;
    boolean hasOperation();
    String getOperation();
    
    // optional string fault = 3;
    boolean hasFault();
    String getFault();
    
    // repeated .org.savara.sam.activity.Message message = 4;
    java.util.List<org.savara.sam.activity.ServiceModel.Message> 
        getMessageList();
    org.savara.sam.activity.ServiceModel.Message getMessage(int index);
    int getMessageCount();
    java.util.List<? extends org.savara.sam.activity.ServiceModel.MessageOrBuilder> 
        getMessageOrBuilderList();
    org.savara.sam.activity.ServiceModel.MessageOrBuilder getMessageOrBuilder(
        int index);
    
    // required .org.savara.sam.activity.ServiceInvocation.InvocationType invocationType = 5 [default = REQUEST];
    boolean hasInvocationType();
    org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType getInvocationType();
  }
  public static final class ServiceInvocation extends
      com.google.protobuf.GeneratedMessage
      implements ServiceInvocationOrBuilder {
    // Use ServiceInvocation.newBuilder() to construct.
    private ServiceInvocation(Builder builder) {
      super(builder);
    }
    private ServiceInvocation(boolean noInit) {}
    
    private static final ServiceInvocation defaultInstance;
    public static ServiceInvocation getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceInvocation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_ServiceInvocation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_ServiceInvocation_fieldAccessorTable;
    }
    
    public enum InvocationType
        implements com.google.protobuf.ProtocolMessageEnum {
      REQUEST(0, 0),
      RESPONSE(1, 1),
      ;
      
      public static final int REQUEST_VALUE = 0;
      public static final int RESPONSE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static InvocationType valueOf(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<InvocationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<InvocationType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InvocationType>() {
              public InvocationType findValueByNumber(int number) {
                return InvocationType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.savara.sam.activity.ServiceModel.ServiceInvocation.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final InvocationType[] VALUES = {
        REQUEST, RESPONSE, 
      };
      
      public static InvocationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private InvocationType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:org.savara.sam.activity.ServiceInvocation.InvocationType)
    }
    
    private int bitField0_;
    // required string serviceType = 1;
    public static final int SERVICETYPE_FIELD_NUMBER = 1;
    private java.lang.Object serviceType_;
    public boolean hasServiceType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getServiceType() {
      java.lang.Object ref = serviceType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serviceType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getServiceTypeBytes() {
      java.lang.Object ref = serviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string operation = 2;
    public static final int OPERATION_FIELD_NUMBER = 2;
    private java.lang.Object operation_;
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          operation_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string fault = 3;
    public static final int FAULT_FIELD_NUMBER = 3;
    private java.lang.Object fault_;
    public boolean hasFault() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getFault() {
      java.lang.Object ref = fault_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fault_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFaultBytes() {
      java.lang.Object ref = fault_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fault_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .org.savara.sam.activity.Message message = 4;
    public static final int MESSAGE_FIELD_NUMBER = 4;
    private java.util.List<org.savara.sam.activity.ServiceModel.Message> message_;
    public java.util.List<org.savara.sam.activity.ServiceModel.Message> getMessageList() {
      return message_;
    }
    public java.util.List<? extends org.savara.sam.activity.ServiceModel.MessageOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    public int getMessageCount() {
      return message_.size();
    }
    public org.savara.sam.activity.ServiceModel.Message getMessage(int index) {
      return message_.get(index);
    }
    public org.savara.sam.activity.ServiceModel.MessageOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }
    
    // required .org.savara.sam.activity.ServiceInvocation.InvocationType invocationType = 5 [default = REQUEST];
    public static final int INVOCATIONTYPE_FIELD_NUMBER = 5;
    private org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType invocationType_;
    public boolean hasInvocationType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType getInvocationType() {
      return invocationType_;
    }
    
    private void initFields() {
      serviceType_ = "";
      operation_ = "";
      fault_ = "";
      message_ = java.util.Collections.emptyList();
      invocationType_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType.REQUEST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasServiceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInvocationType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMessageCount(); i++) {
        if (!getMessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOperationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFaultBytes());
      }
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(4, message_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(5, invocationType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOperationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFaultBytes());
      }
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, message_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, invocationType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.savara.sam.activity.ServiceModel.ServiceInvocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.savara.sam.activity.ServiceModel.ServiceInvocation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.savara.sam.activity.ServiceModel.ServiceInvocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_ServiceInvocation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.savara.sam.activity.ServiceModel.internal_static_org_savara_sam_activity_ServiceInvocation_fieldAccessorTable;
      }
      
      // Construct using org.savara.sam.activity.ServiceModel.ServiceInvocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serviceType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fault_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          messageBuilder_.clear();
        }
        invocationType_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.savara.sam.activity.ServiceModel.ServiceInvocation.getDescriptor();
      }
      
      public org.savara.sam.activity.ServiceModel.ServiceInvocation getDefaultInstanceForType() {
        return org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance();
      }
      
      public org.savara.sam.activity.ServiceModel.ServiceInvocation build() {
        org.savara.sam.activity.ServiceModel.ServiceInvocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.savara.sam.activity.ServiceModel.ServiceInvocation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.savara.sam.activity.ServiceModel.ServiceInvocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.savara.sam.activity.ServiceModel.ServiceInvocation buildPartial() {
        org.savara.sam.activity.ServiceModel.ServiceInvocation result = new org.savara.sam.activity.ServiceModel.ServiceInvocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceType_ = serviceType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fault_ = fault_;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.invocationType_ = invocationType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.savara.sam.activity.ServiceModel.ServiceInvocation) {
          return mergeFrom((org.savara.sam.activity.ServiceModel.ServiceInvocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.savara.sam.activity.ServiceModel.ServiceInvocation other) {
        if (other == org.savara.sam.activity.ServiceModel.ServiceInvocation.getDefaultInstance()) return this;
        if (other.hasServiceType()) {
          setServiceType(other.getServiceType());
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasFault()) {
          setFault(other.getFault());
        }
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000008);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        if (other.hasInvocationType()) {
          setInvocationType(other.getInvocationType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasServiceType()) {
          
          return false;
        }
        if (!hasInvocationType()) {
          
          return false;
        }
        for (int i = 0; i < getMessageCount(); i++) {
          if (!getMessage(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceType_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              operation_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fault_ = input.readBytes();
              break;
            }
            case 34: {
              org.savara.sam.activity.ServiceModel.Message.Builder subBuilder = org.savara.sam.activity.ServiceModel.Message.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessage(subBuilder.buildPartial());
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType value = org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                invocationType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string serviceType = 1;
      private java.lang.Object serviceType_ = "";
      public boolean hasServiceType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getServiceType() {
        java.lang.Object ref = serviceType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serviceType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setServiceType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceType_ = value;
        onChanged();
        return this;
      }
      public Builder clearServiceType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceType_ = getDefaultInstance().getServiceType();
        onChanged();
        return this;
      }
      void setServiceType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        serviceType_ = value;
        onChanged();
      }
      
      // optional string operation = 2;
      private java.lang.Object operation_ = "";
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          operation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOperation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        operation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      void setOperation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        operation_ = value;
        onChanged();
      }
      
      // optional string fault = 3;
      private java.lang.Object fault_ = "";
      public boolean hasFault() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getFault() {
        java.lang.Object ref = fault_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fault_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFault(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fault_ = value;
        onChanged();
        return this;
      }
      public Builder clearFault() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fault_ = getDefaultInstance().getFault();
        onChanged();
        return this;
      }
      void setFault(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        fault_ = value;
        onChanged();
      }
      
      // repeated .org.savara.sam.activity.Message message = 4;
      private java.util.List<org.savara.sam.activity.ServiceModel.Message> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          message_ = new java.util.ArrayList<org.savara.sam.activity.ServiceModel.Message>(message_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.savara.sam.activity.ServiceModel.Message, org.savara.sam.activity.ServiceModel.Message.Builder, org.savara.sam.activity.ServiceModel.MessageOrBuilder> messageBuilder_;
      
      public java.util.List<org.savara.sam.activity.ServiceModel.Message> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      public org.savara.sam.activity.ServiceModel.Message getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      public Builder setMessage(
          int index, org.savara.sam.activity.ServiceModel.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMessage(
          int index, org.savara.sam.activity.ServiceModel.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMessage(org.savara.sam.activity.ServiceModel.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMessage(
          int index, org.savara.sam.activity.ServiceModel.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMessage(
          org.savara.sam.activity.ServiceModel.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMessage(
          int index, org.savara.sam.activity.ServiceModel.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMessage(
          java.lang.Iterable<? extends org.savara.sam.activity.ServiceModel.Message> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          super.addAll(values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      public org.savara.sam.activity.ServiceModel.Message.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      public org.savara.sam.activity.ServiceModel.MessageOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.savara.sam.activity.ServiceModel.MessageOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      public org.savara.sam.activity.ServiceModel.Message.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            org.savara.sam.activity.ServiceModel.Message.getDefaultInstance());
      }
      public org.savara.sam.activity.ServiceModel.Message.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, org.savara.sam.activity.ServiceModel.Message.getDefaultInstance());
      }
      public java.util.List<org.savara.sam.activity.ServiceModel.Message.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.savara.sam.activity.ServiceModel.Message, org.savara.sam.activity.ServiceModel.Message.Builder, org.savara.sam.activity.ServiceModel.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.savara.sam.activity.ServiceModel.Message, org.savara.sam.activity.ServiceModel.Message.Builder, org.savara.sam.activity.ServiceModel.MessageOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      
      // required .org.savara.sam.activity.ServiceInvocation.InvocationType invocationType = 5 [default = REQUEST];
      private org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType invocationType_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType.REQUEST;
      public boolean hasInvocationType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType getInvocationType() {
        return invocationType_;
      }
      public Builder setInvocationType(org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        invocationType_ = value;
        onChanged();
        return this;
      }
      public Builder clearInvocationType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        invocationType_ = org.savara.sam.activity.ServiceModel.ServiceInvocation.InvocationType.REQUEST;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.savara.sam.activity.ServiceInvocation)
    }
    
    static {
      defaultInstance = new ServiceInvocation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.savara.sam.activity.ServiceInvocation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_savara_sam_activity_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_savara_sam_activity_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_savara_sam_activity_ServiceInvocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_savara_sam_activity_ServiceInvocation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ServiceModel.proto\022\027org.savara.sam.act" +
      "ivity\"/\n\007Message\022\023\n\013messageType\030\001 \002(\t\022\017\n" +
      "\007content\030\002 \001(\t\"\206\002\n\021ServiceInvocation\022\023\n\013" +
      "serviceType\030\001 \002(\t\022\021\n\toperation\030\002 \001(\t\022\r\n\005" +
      "fault\030\003 \001(\t\0221\n\007message\030\004 \003(\0132 .org.savar" +
      "a.sam.activity.Message\022Z\n\016invocationType" +
      "\030\005 \002(\01629.org.savara.sam.activity.Service" +
      "Invocation.InvocationType:\007REQUEST\"+\n\016In" +
      "vocationType\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001B" +
      "\'\n\027org.savara.sam.activityB\014ServiceModel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_savara_sam_activity_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_savara_sam_activity_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_savara_sam_activity_Message_descriptor,
              new java.lang.String[] { "MessageType", "Content", },
              org.savara.sam.activity.ServiceModel.Message.class,
              org.savara.sam.activity.ServiceModel.Message.Builder.class);
          internal_static_org_savara_sam_activity_ServiceInvocation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_savara_sam_activity_ServiceInvocation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_savara_sam_activity_ServiceInvocation_descriptor,
              new java.lang.String[] { "ServiceType", "Operation", "Fault", "Message", "InvocationType", },
              org.savara.sam.activity.ServiceModel.ServiceInvocation.class,
              org.savara.sam.activity.ServiceModel.ServiceInvocation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
